services:
  redis:
    image: redis
    ports:
      - 6379:6379

  mysqldb:
    image: mysql
    volumes:
      - ./mysqldb:/var/lib/mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - 3306:3306

  wallet-service:
    build: .
    environment:
      NODE_ENV: test
      PORT: '3005'
      REDIS_URL: redis://redis:6379
      IOS_BUILD_NUMBER: 20250320005947,1.3.5
      ANDROID_BUILD_NUMBER: 11000,0.11.0
      GATEMAN_KEY: 34982gb2745h28y450t2745t2087yt24857
      DEFAULT_OTP: 000000
    depends_on:
      - redis
      - mysqldb
    command:
      - /bin/sh
      - -c
      - yarn start

  app:
    build: .
    environment:
      NODE_ENV: test
      PORT: '3005'
      REDIS_URL: redis://redis:6379
      IOS_BUILD_NUMBER: 20250320005947,1.3.5
      ANDROID_BUILD_NUMBER: 11000,0.11.0
      GATEMAN_KEY: 34982gb2745h28y450t2745t2087yt24857
      DEFAULT_OTP: 000000
    depends_on:
      - redis
      - mysqldb
      - wallet-service
    command:
      - /bin/sh
      - -c
      - |
        chmod +x ./wait-for-it.sh && \
        ./wait-for-it.sh -t 60 wallet-service:3005 -- yarn test
