services:
  redis:
    image: redis
    ports:
      - 6379:6379

  mysqldb:
    image: mysql
    volumes:
      - ./mysqldb:/var/lib/mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - 3306:3306

